version: '3'

tasks:
  default:
    desc: "Set up ETkI for use"
    cmds:
      - mv src/* .
      - rm *.md
      - rm LICENSE
      - rm -rf tests
      - rm pyproject.toml
  clean:
    desc: "Remove everything except library files - run this after task."
    cmds:
      - rm Makefile
      - rm Taskfile.yml
