name: Ubuntu Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 .
      continue-on-error: true
    - name: Create issue if failed
      run: |
        if [[ "$?" -ne 0 ]]; then
          gh issue create --title "Style guide not followed" --body "See actions" --label "Flake" --assignee "aarikpokras" -R aarikpokras/etki
          exit 1
        fi
